mi:
  saludo : hola servidor web 
  lista:
    valores: test,uno,dos,tres

db:
  claveValor : "{\
  urlBase: 'urlBase',\
  nombre: 'nombre',\
  port: 'port'}"
  host: "localhost"
  port: 1000

management:
  endpoints:
    web:
      exposure:
        include: "*"
