
mi:
  saludo : hola
  lista.valores: uno,dos,tres

db:
  claveValor : "{\
  urlBase: 'urlBase',\
  nombre: 'nombre',\
  port: 'port'}"
  host: "localhost"
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: "*"